Port 3000
Listen 127.0.0.1
Timeout 600
Allow 127.0.0.1
MaxClients 1000

upstream none "storage.googleapis.com"
upstream none "cdn.highpay-ads.com"
upstream none "fonts.gstatic.com"
upstream none "challenges.cloudflare.com"
upstream none "static.cloudflareinsights.com"
upstream none "static.a-ads.com"
upstream none "fconverter.vipb.top"
upstream none "telead.mail.name.ng"
upstream none "static.surfe.pro"
upstream none "static.surfe.be"
upstream none "telegram.org"
upstream none "www.google.com"
upstream none "clients.google.com"
upstream none "clients2.google.com"
upstream none "t.me"
upstream none "android.clients.google.com"
upstream none "mtalk.google.com"
upstream none "accounts.google.com"
upstream none "doc.mail.name.ng"
upstream none "content-autofill.googleapis.com"
upstream none "redirector.gvt1.com"
upstream none "www.googletagmanager.com"
upstream none "cdn4.telesco.pe"


upstream http GCDAWaTh:W8xFhErW@gateway.aluvia.io:8080
