Port 3000
Listen 127.0.0.1
Timeout 600
Allow 127.0.0.1
MaxClients 10000




upstream http VgZBNQWZ:2ku8hF3R@gateway.aluvia.io:8080 "cpmlink.co"
upstream http VgZBNQWZ:2ku8hF3R@gateway.aluvia.io:8080 "cpmlink.pro"
